/** Единый справочник надписей для UI плагина. */

export const UI_LABELS = {
  common: {
    save: "Сохранить",
    cancel: "Отмена",
    ok: "ОК",
    add: "Добавить",
    edit: "Изменить",
    copy: "Копировать",
    delete: "Удалить",
    empty: "Пусто",
  },
  errors: {
    loadModules: "Не загружены модули",
    loadData: "Не удалось загрузить данные",
    render: "Ошибка отображения. Проверьте консоль.",
    renderShort: "Ошибка отрисовки",
    fileNotFound: (path: string) => `Ошибка: Файл "${path}" не найден.`,
  },
  tasks: {
    total: "Всего задач",
    noActive: "Нет активных задач.",
    noTasks: "Нет задач.",
    noNotes: "Нет заметок.",
    ungrouped: "Задачи без группы",
    columns: {
      task: "Задача",
      context: "Контекст",
      project: "Проект",
      environment: "Окружение",
      status: "Статус",
      deadline: "Дедлайн",
      time: "Срок",
    },
    defaultStatus: "В работе",
  },
  loader: {
    loading: "Загрузка...",
  },
  trash: {
    loadError: "Корзина",
    cleared: "Корзина очищена",
    alreadyEmpty: "Корзина уже пуста",
    clear: "Очистить",
    empty: "Пусто",
    completedBadge: "Выполнено",
  },
  inbox: {
    loadError: "Inbox",
    loadDataError: "Не удалось загрузить данные Inbox.",
    empty: "Пусто",
    addPlaceholder: "Добавить запись",
    actions: { done: "Выполнено", task: "Задача", edit: "Изменить", reminder: "Напоминание", delete: "Удалить" },
    archiveTitle: "Архив",
    notices: { updated: "Запись обновлена", emptyName: "Ошибка: имя задачи не может быть пустым.", remindersCreated: "Создан файл Reminders.md", duplicate: "Такая запись уже есть в блокноте", movedToTrash: "Запись перемещена в корзину" },
  },
  reminders: {
    loadError: "Напоминания",
    errorNotice: "Ошибка напоминаний",
    empty: "Нет активных напоминаний",
    addPlaceholder: "Добавить напоминание",
    edit: "Изменить",
    delete: "Удалить",
    sections: { overdue: "Просрочено", today: "Сегодня", tomorrow: "Завтра", upcoming: "Предстоящие", archive: "Архив" },
    modal: {
      title: "Настройка напоминания",
      textLabel: "Текст напоминания",
      dateLabel: "Дата и время:",
      recurrenceLabel: "Повторение:",
      noRecurrence: "Без повтора",
      days: "Дней",
      weeks: "Недель",
      months: "Месяцев",
      years: "Лет",
      fillRequired: "Заполните текст и дату",
    },
    notices: {
      completed: "Напоминание выполнено",
      updated: "Напоминание обновлено",
      movedToTrash: "Напоминание перемещено в корзину",
      nextCreated: (amount: number, unit: string) => `Создана следующая задача: через ${amount} ${unit}`,
      editNotFound: "Не удалось найти задачу для редактирования.",
      deleteNotFound: "Не удалось найти задачу для удаления.",
      completeNotFound: "Не удалось найти задачу для завершения.",
      addedTo: (name: string) => `Напоминание добавлено в ${name}`,
      fileCreated: "Создан файл Reminders.md",
      invalidDate: "Некорректная дата",
      trashNotFound: (path: string) => `Файл ${path} не найден, задача удалена безвозвратно.`,
    },
    snooze: {
      doneBtn: "✅ Выполнено",
      oneHourBtn: "🕐 Отложить на 1 час",
      tomorrowBtn: "☀️ Отложить на завтра",
      pickDateBtn: "📅 Выбрать дату...",
      pickerTitle: "Выберите время переноса",
      done: "Задача выполнена!",
      oneHour: "Перенесено на 1 час",
      tomorrow: "Перенесено на завтра",
      rescheduled: (date: string) => `Перенесено на ${date}`,
    },
  },
  gamification: {
    progress: "Прогресс",
    levelLabel: "Уровень",
    xpToLevel: (current: number, need: number, level: number) => `${current} / ${need} ХР до уровня ${level}`,
    gold: "Gold",
    completed: "Выполненные",
    streaks: "Стрики",
    shopTitle: "МАГАЗИН",
    management: "Управление",
    purchased: "Купленное",
    buy: "Купить",
    name: "Название",
    price: "Цена",
    task: "Задача",
    deadline: "Срок",
    completedOn: "Выполнено",
    reward: "Награда",
    streak: "Стрик",
    days: "Дней",
    day: "день",
    daysCount: (n: number) => (n === 1 ? "1 день" : `${n} дней`),
    clearHistory: "Очистить историю",
    currentMonth: "Текущий месяц",
    rewardsReceived: "Награды получены",
    returnedToWork: "Вернулась в работу",
    rewardLine: (xp: number, gold: number) => `+${xp} XP, +${gold} Gold`,
    shopTitleShort: "Магазин",
    addItem: "Добавить лот",
    description: "Описание",
  },
  activities: {
    title: "Сегодняшние активности",
    doneToday: "Сделано сегодня",
    yesterday: "Вчера",
    daysAgo: (n: number) => (n === 1 ? "1 день назад" : n < 5 ? `${n} дня назад` : `${n} дней назад`),
    weekAgo: "Неделю назад",
    never: "Никогда",
    charts: "Статистика",
    allActivities: "Активности",
    allActivitiesTitle: "Выбор активностей на сегодня",
    poolListTitle: "Список возможных активностей",
    addActivity: "Добавить",
    addActivityLong: "Добавить активность",
    addPlaceholder: "Название активности",
    selectTodayTitle: "Отметить на сегодня",
    empty: "Нет активностей. Добавьте первую.",
    emptyToday: "Ничего не отмечено на сегодня",
    statsTitle: "Статистика по активностям",
    currentMonth: "Текущий месяц",
    chartLastDays: "За последние 30 дней",
    rewardNotice: "+2 XP, +1 Gold",
  },
} as const;
